version: '3'
services:
  main:
    image: stayradiated/zwolf-signal:latest
    build: '.'
    restart: unless-stopped
    environment:
      - "OWNER_NUMBER=${OWNER_NUMBER}"
      - "BOT_NUMBER=${BOT_NUMBER}"
      - "AMQP_ADDRESS=amqp://guest:guest@rabbitmq:5672/"
    volumes:
      - "./signal-cli-config:/root/.local/share/signal-cli"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.9-alpine
    restart: unless-stopped
