version: '3'
services:
  main:
    image: stayradiated/zwolf-signal:latest
    build: '.'
    environment:
      - "OWNER_NUMBER=${OWNER_NUMBER}"
      - "ASSISTANT_NUMBER=${ASSISTANT_NUMBER}"
      - "ASSISTANT_FOLDER=/root"
    volumes:
      - "./signal-cli-config:/root/.local/share/signal-cli"
