version: '3'
services:
  main:
    image: stayradiated/zwolf-signal:latest
    build: '.'
    environment:
      - "OWNER_NUMBER=${OWNER_NUMBER}"
      - "BOT_NUMBER=${BOT_NUMBER}"
    volumes:
      - "./signal-cli-config:/root/.local/share/signal-cli"
